In [1]:
# https://alstn2468.github.io/2019/BasicChapter5_2/
# lab 04-1: multi-variable linear regression을 TensorFlow에서 구현하기
import tensorflow as tf

x1_data = [73., 93., 89., 96., 73.]
x2_data = [80., 88., 91., 98., 66.]
x3_data = [75., 93., 90., 100., 70.]
y_data = [152., 185., 180., 196., 142.]

x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)

Y = tf.placeholder(tf.float32)

w1 = tf.Variable(tf.random_normal([1]), name='weight1')
w2 = tf.Variable(tf.random_normal([1]), name='weight2')
w3 = tf.Variable(tf.random_normal([1]), name='weight3')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = x1 * w1 + x2 *w2 + x3 * w3 + b

cost = tf.reduce_mean(tf.square(hypothesis - Y))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

sess = tf.Session()
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                                  feed_dict={x1: x1_data,
                                             x2: x2_data,
                                             x3: x3_data,
                                             Y : y_data})
    if step % 100 == 0:
        print(step, "Cost:", cost_val, "\nPrediction:\n", hy_val)

0 Cost: 148928.62 
Prediction:
 [-182.61755 -232.4636  -222.16943 -244.36559 -178.525  ]
100 Cost: 28.827305 
Prediction:
 [159.55673 179.20346 183.24539 197.14662 135.55135]
200 Cost: 27.322779 
Prediction:
 [159.35081 179.34444 183.18205 197.10266 135.7348 ]
300 Cost: 25.897644 
Prediction:
 [159.15039 179.48166 183.1204  197.05989 135.91331]
400 Cost: 24.547543 
Prediction:
 [158.95529 179.61523 183.0604  197.01831 136.08705]
500 Cost: 23.268747 
Prediction:
 [158.7654  179.74522 183.00195 196.97787 136.25609]
600 Cost: 22.057327 
Prediction:
 [158.58055 179.87175 182.94508 196.93857 136.42061]
700 Cost: 20.909788 
Prediction:
 [158.40063 179.99492 182.88971 196.90034 136.58069]
800 Cost: 19.822796 
Prediction:
 [158.2255  180.11478 182.8358  196.86317 136.73645]
900 Cost: 18.793118 
Prediction:
 [158.05504 180.23146 182.78333 196.82704 136.88803]
1000 Cost: 17.817677 
Prediction:
 [157.8891  180.34503 182.73227 196.79192 137.03555]
1100 Cost: 16.893724 
Prediction:
 [157.72758 180.

In [2]:
x_data = [
    [73., 80., 75.],
    [93., 88., 93.],
    [89., 91., 90.],
    [96., 98., 100.],
    [73., 66., 70.],
]
y_data = [
    [152.],
    [185.],
    [180.],
    [196.],
    [142.],
]

X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = tf.matmul(X, W) + b
cost = tf.reduce_mean(tf.square(hypothesis - Y))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

sess = tf.Session()
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                                   feed_dict={X: x_data, Y: y_data})
    if step % 200 == 0:
        print(step, "Cost:", cost_val, "\nPrediction:\n", hy_val)

0 Cost: 24025.994 
Prediction:
 [[295.4358 ]
 [345.20215]
 [345.08685]
 [376.72595]
 [260.2196 ]]
200 Cost: 25.043676 
Prediction:
 [[157.59573]
 [180.2565 ]
 [182.18532]
 [199.36252]
 [134.56204]]
400 Cost: 22.594318 
Prediction:
 [[157.23122]
 [180.50743]
 [182.07497]
 [199.27235]
 [134.90007]]
600 Cost: 20.395504 
Prediction:
 [[156.88614]
 [180.74501]
 [181.97052]
 [199.18652]
 [135.22052]]
800 Cost: 18.421568 
Prediction:
 [[156.55952]
 [180.96999]
 [181.8718 ]
 [199.10489]
 [135.52438]]
1000 Cost: 16.649364 
Prediction:
 [[156.25035]
 [181.18295]
 [181.77835]
 [199.02711]
 [135.81247]]
1200 Cost: 15.058203 
Prediction:
 [[155.9577 ]
 [181.3846 ]
 [181.68999]
 [198.95308]
 [136.08563]]
1400 Cost: 13.6294985 
Prediction:
 [[155.68073]
 [181.57552]
 [181.60641]
 [198.88255]
 [136.34465]]
1600 Cost: 12.346576 
Prediction:
 [[155.41858]
 [181.75624]
 [181.52739]
 [198.81537]
 [136.59029]]
1800 Cost: 11.19444 
Prediction:
 [[155.17046]
 [181.9273 ]
 [181.45262]
 [198.75131]
 [136.82321