In [1]:
import tensorflow as tf
import pandas as pd

In [4]:
파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'
아이리스 = pd.read_csv(파일경로)
아이리스 = pd.get_dummies(아이리스)

아이리스.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭  품종_setosa  품종_versicolor  품종_virginica
0   5.1  3.5    1.4   0.2          1              0             0
1   4.9  3.0    1.4   0.2          1              0             0
2   4.7  3.2    1.3   0.2          1              0             0
3   4.6  3.1    1.5   0.2          1              0             0
4   5.0  3.6    1.4   0.2          1              0             0

In [5]:
독립 = 아이리스[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
종속 = 아이리스[['품종_setosa', '품종_versicolor', '품종_virginica']]
print(독립.shape, 종속.shape)

(150, 4) (150, 3)


In [6]:
X = tf.keras.layers.Input(shape=[4])
Y = tf.keras.layers.Dense(3, activation='softmax')(X)
model = tf.keras.models.Model(X, Y)
model.compile(loss='categorical_crossentropy',
              metrics='accuracy')

In [7]:
model.fit(독립, 종속, epochs=1000)

Epoch 1/1000
5/5 [==============================] - 1s 3ms/step - loss: 1.4994 - accuracy: 0.3207
Epoch 2/1000
5/5 [==============================] - 0s 2ms/step - loss: 1.3509 - accuracy: 0.3594
Epoch 3/1000
5/5 [==============================] - 0s 2ms/step - loss: 1.3492 - accuracy: 0.3177
Epoch 4/1000
5/5 [==============================] - 0s 2ms/step - loss: 1.2991 - accuracy: 0.3273
Epoch 5/1000
5/5 [==============================] - 0s 2ms/step - loss: 1.1930 - accuracy: 0.3601
Epoch 6/1000
5/5 [==============================] - 0s 2ms/step - loss: 1.2184 - accuracy: 0.3249
Epoch 7/1000
5/5 [==============================] - 0s 2ms/step - loss: 1.1408 - accuracy: 0.3313
Epoch 8/1000
5/5 [==============================] - 0s 2ms/step - loss: 1.1209 - accuracy: 0.3212
Epoch 9/1000
5/5 [==============================] - 0s 2ms/step - loss: 1.0897 - accuracy: 0.2767
Epoch 10/1000
5/5 [==============================] - 0s 2ms/step - loss: 1.1327 - accuracy: 0.2019
Epoch 11/1000
5/5 [

In [8]:
print(model.predict(독립[:5]))
print(종속[:5])

[[9.9930274e-01 6.9724425e-04 4.1601012e-08]
 [9.9661034e-01 3.3890272e-03 5.6674821e-07]
 [9.9866617e-01 1.3336912e-03 1.5542498e-07]
 [9.9644583e-01 3.5536147e-03 6.3976279e-07]
 [9.9948466e-01 5.1534059e-04 2.6962002e-08]]
   품종_setosa  품종_versicolor  품종_virginica
0          1              0             0
1          1              0             0
2          1              0             0
3          1              0             0
4          1              0             0


In [9]:
print(model.get_weights())

[array([[ 0.1862848 ,  0.0842709 , -0.4495658 ],
       [ 3.7278554 ,  0.6009404 , -1.2467794 ],
       [-3.8706052 , -0.57386446,  0.40995675],
       [-4.141046  , -1.5206769 ,  2.453285  ]], dtype=float32), array([ 2.0260673,  1.0833532, -1.6259683], dtype=float32)]
