In [1]:
##########################
# 라이브러리 사용
import tensorflow as tf
import pandas as pd
 
###########################
# 1.과거의 데이터를 준비합니다.
파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/boston.csv'
보스턴 = pd.read_csv(파일경로)
 
# 종속변수, 독립변수
독립 = 보스턴[['crim', 'zn', 'indus', 'chas', 'nox', 
            'rm', 'age', 'dis', 'rad', 'tax',
            'ptratio', 'b', 'lstat']]
종속 = 보스턴[['medv']]
print(독립.shape, 종속.shape)
 
###########################

(506, 13) (506, 1)


In [3]:
X = tf.keras.layers.Input(shape=[13])
H = tf.keras.layers.Dense(10, activation='swish')(X)
Y = tf.keras.layers.Dense(1)(H)
model = tf.keras.models.Model(X, Y)
model.compile(loss='mse')

In [4]:
model.summary()


Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_2 (InputLayer)         [(None, 13)]              0         
_________________________________________________________________
dense_1 (Dense)              (None, 10)                140       
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 11        
Total params: 151
Trainable params: 151
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model.fit(독립, 종속, epochs=10000)

Epoch 2349/10000
5/5 [==============================] - 0s 4ms/step - loss: 0.0426 - accuracy: 0.9867
Epoch 2350/10000
5/5 [==============================] - 0s 4ms/step - loss: 0.0377 - accuracy: 0.9933
Epoch 2351/10000
5/5 [==============================] - 0s 3ms/step - loss: 0.0412 - accuracy: 0.9867
Epoch 2352/10000
5/5 [==============================] - 0s 2ms/step - loss: 0.0426 - accuracy: 0.9867
Epoch 2353/10000
5/5 [==============================] - 0s 2ms/step - loss: 0.0426 - accuracy: 0.9867
Epoch 2354/10000
5/5 [==============================] - 0s 2ms/step - loss: 0.0454 - accuracy: 0.9800
Epoch 2355/10000
5/5 [==============================] - 0s 4ms/step - loss: 0.0518 - accuracy: 0.9867
Epoch 2356/10000
5/5 [==============================] - 0s 3ms/step - loss: 0.0454 - accuracy: 0.9800
Epoch 2357/10000
5/5 [==============================] - 0s 3ms/step - loss: 0.0496 - accuracy: 0.9867
Epoch 2358/10000
5/5 [==============================] - 0s 3ms/step - loss: 0.0446

In [6]:
파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'
아이리스 = pd.read_csv(파일경로)
 
# 원핫인코딩
아이리스 = pd.get_dummies(아이리스)
 
# 종속변수, 독립변수
독립 = 아이리스[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
종속 = 아이리스[['품종_setosa', '품종_versicolor', '품종_virginica']]
print(독립.shape, 종속.shape)

(150, 4) (150, 3)


In [7]:
X = tf.keras.layers.Input(shape=[4])
H = tf.keras.layers.Dense(8, activation="swish")(X)
H = tf.keras.layers.Dense(8, activation="swish")(H)
H = tf.keras.layers.Dense(8, activation="swish")(H)
Y = tf.keras.layers.Dense(3, activation='softmax')(H)
model = tf.keras.models.Model(X, Y)
model.compile(loss='categorical_crossentropy',
              metrics='accuracy')

In [8]:
model.summary()


Model: "model_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_3 (InputLayer)         [(None, 4)]               0         
_________________________________________________________________
dense_3 (Dense)              (None, 8)                 40        
_________________________________________________________________
dense_4 (Dense)              (None, 8)                 72        
_________________________________________________________________
dense_5 (Dense)              (None, 8)                 72        
_________________________________________________________________
dense_6 (Dense)              (None, 3)                 27        
Total params: 211
Trainable params: 211
Non-trainable params: 0
_________________________________________________________________


In [9]:
model.fit(독립, 종속, epochs=100)

Epoch 1/100
5/5 [==============================] - 1s 2ms/step - loss: 1.1772 - accuracy: 0.3120
Epoch 2/100
5/5 [==============================] - 0s 2ms/step - loss: 1.1021 - accuracy: 0.3438
Epoch 3/100
5/5 [==============================] - 0s 2ms/step - loss: 1.0953 - accuracy: 0.2773
Epoch 4/100
5/5 [==============================] - 0s 2ms/step - loss: 1.0411 - accuracy: 0.3555
Epoch 5/100
5/5 [==============================] - 0s 2ms/step - loss: 1.0177 - accuracy: 0.3812
Epoch 6/100
5/5 [==============================] - 0s 2ms/step - loss: 0.9975 - accuracy: 0.4302
Epoch 7/100
5/5 [==============================] - 0s 2ms/step - loss: 0.9647 - accuracy: 0.5323
Epoch 8/100
5/5 [==============================] - 0s 2ms/step - loss: 0.9447 - accuracy: 0.5714
Epoch 9/100
5/5 [==============================] - 0s 2ms/step - loss: 0.9527 - accuracy: 0.5673
Epoch 10/100
5/5 [==============================] - 0s 2ms/step - loss: 0.9320 - accuracy: 0.6277
Epoch 11/100
5/5 [===========

In [10]:
print(model.predict(독립[:5]))
print(종속[:5])

[[9.9798191e-01 2.0173085e-03 6.8851318e-07]
 [9.9477732e-01 5.2193110e-03 3.2729756e-06]
 [9.9611521e-01 3.8821385e-03 2.6627058e-06]
 [9.9299085e-01 7.0026591e-03 6.5058448e-06]
 [9.9809796e-01 1.9013068e-03 6.9390455e-07]]
   품종_setosa  품종_versicolor  품종_virginica
0          1              0             0
1          1              0             0
2          1              0             0
3          1              0             0
4          1              0             0
